### ISSUE TITLE
Tests for clearsky.reno fail with pvlib 0.8.1

### ISSUE THREAD

**Issue by wfvining** [pvlib/pvanalytics#105]
PVLib 0.8.1 changed the labeling of clear-sky periods (https://github.com/pvlib/pvlib-python/pull/1074) which is resulting in a test failures in `test_clearsky.py`.

The change in pvlib labels windows on the center by default, while previous behavior labeled on the left. We probably want to accept the new default behavior from PVLib (updating the tests to match) and expose the new `align` parameter in `pvanalytics.clearsky.reno`.

**Comment by cwhanse** [comment]
> The change in pvlib labels windows on the left by default, while previous behavior used centered labels. 

Other way around; before v0.8.1, pvlib used left labels. pvlib v0.8.1 uses centered labels.

**Comment by wfvining** [comment]
> Other way around; before v0.8.1, pvlib used left labels. pvlib v0.8.1 uses centered labels.

Thanks, updated.

**Comment by wfvining** [comment]
Actually, the alignment is not exposed in the pvlib API. We should probably just accept the centered labels here, and remove/rewrite tests that relied on left-aligned labels. I'm thinking that my approach to testing this function was flawed to begin with, it might be better to mock the pvlib function and check that the window/scale are computed correctly and passed the pvlib function (otherwise we are spending a bunch of effort testing code that isn't even part of pvanalytics).

**Comment by cwhanse** [comment]
Tests for `clearsky.reno` fail because of a bug in `pvlib.clearsky` #https://github.com/pvlib/pvlib-python/issues/1241#
