### ISSUE TITLE
Sphinx docs don't show example usage

### ISSUE THREAD

**Issue by kanderso-nrel** [pvlib/pvanalytics#125]
Currently the sphinx docs are focused primarily on API documentation.  Of course that's a necessary component for good docs, but example usage would be a good addition.  #124 adds one example file and I think the plan is for future PRs to do the same.  I'm aware of a few common ways of showing example usage in sphinx docs (probably there are more I'm not thinking of):

1. **Docstring examples**: Numpydoc style allows an `Examples` section with short code input and output snippets ([ref](https://numpy.org/doc/stable/reference/generated/numpy.sin.html)).  For functions with simple inputs and outputs this can be a good option, but I'm not sure it's suitable for pvanalytics functions, which typically have big timeseries inputs and outputs.  Here's an example of what it looks like from numpy: https://numpy.org/doc/stable/reference/generated/numpy.sin.html
2. **Example scripts using sphinx-gallery**: [sphinx-gallery](https://sphinx-gallery.github.io/stable/index.html) is a popular sphinx extension for building galleries of example scripts like pvlib's [example gallery](https://pvlib-python.readthedocs.io/en/latest/gallery/).  It's better suited for examples longer than just one line.  Example code is stored in .py files which get executed during the docs build.
3. **Example scripts using nbsphinx**: [nbsphinx](https://nbsphinx.readthedocs.io/en/latest/subdir/gallery.html) can do galleries similar to those of `sphinx-gallery`, but using jupyter notebooks instead of .py files for the source.  The galleries are not quite as nice as those of `sphinx-gallery` because intersphinx linking doesn't work in nbsphinx galleries.  The benefit here is that it uses the output stored in the notebook file, meaning the examples do not have to be executed during the docs build.  We use it for the RdTools [gallery](https://rdtools.readthedocs.io/en/stable/examples.html) because the examples take a long time to run. 

Of these three I think option 2 makes the most sense for pvanalytics, at least for now: single-line examples seems too limiting, and notebooks are a pain to manage in git repos.  If we eventually find ourselves unhappy about docs builds taking too long, or maybe some example can't be run on the CI for some reason, we can always switch over to the notebook-based galleries.

Any thoughts?  I'll volunteer to set up `sphinx-gallery` if others agree it's the way to go.

**Comment by kperrynrel** [comment]
I'm +1 on the sphinx-gallery. I think the jupyter notebooks can get kind of messy, and this seems like a cleaner, more professional approach for our documentation.

**Comment by cwhanse** [comment]
+1 to sphinx-gallery, and no objection to docstring examples if circumstances warrant.
