### ISSUE TITLE
Error in clearsky.reno in newer pandas and numpy versions

### ISSUE THREAD

**Issue by kanderso-nrel** [pvlib/pvanalytics#126]
I know there are some known pandas issues already, but I think this one is new?  This snippet raises an error for some combinations of pandas and numpy:
```python
from pvanalytics.features.clearsky import reno
import pandas as pd

times = pd.date_range('2019-01-01 12:00', freq='1min', periods=3)
ghi = pd.Series([1,1,1], index=times)
reno(ghi, ghi)  # ValueError: clearsky requires regular time intervals of 15m or less
```

It fails with `numpy==1.21.4` + `pandas==1.3.0`.  It works with `numpy==1.19.5` + `pandas==1.2.5`.

This is the issue:

```python
In [7]: pd.Timedelta("1T") / np.timedelta64(1, "60s")
Out[7]: 60.0  # returns 1.0 on older versions
```

I did not do any digging for changes in either library that may have caused this, or whether the issue can be isolated to a change in just one of pandas or numpy.

**Comment by cwhanse** [comment]
This one is new. Probably safer to compute that integer number of minutes with either pandas or numpy but not both. Surprising to see the combination give the wrong answer.

**Comment by cwhanse** [comment]
Would that statement work in newer versions as

```
pd.Timedelta("1T") / np.timedelta64(1, "m")
```

Wondering if it's a change in how numpy handles the time unit string.

**Comment by kanderso-nrel** [comment]
With the newer versions listed above `pd.Timedelta("1T") / np.timedelta64(1, "m")` gives `1.0`, so perhaps that's a suitable fix.  I tend to agree that sticking with all pandas is likely safer.
