### ISSUE TITLE
v0.1.2 release planning

### ISSUE THREAD

**Issue by kanderso-nrel** [pvlib/pvanalytics#144]
It seems prudent to be planning for a release ahead of PVPMC.  The main changes are of course all the gallery examples @kperrynrel has been adding, but I've tagged a few additional things under the [v0.1.2 milestone](https://github.com/pvlib/pvanalytics/milestone/2) I'd like to see get resolved:

- #20
- #112 
- #113
- Organize gallery into sections like we did for [pvlib](https://pvlib-python.readthedocs.io/en/stable/gallery/index.html)?

PRs to review & merge:
- [x] #148 
- [x] #131 
- [x] #145
- [x] #149

Deferred:
- #146

And of course the usual release chores:
- [ ] clean up the whatsnew file formatting
- [ ] include 0.1.2 whatsnew in the index
- [ ] update the whatsnew release date
- [ ] check for missing contributors

I volunteer to submit PRs for those three issues.  Are there any other things people would like to see in the next release?

**Comment by cwhanse** [comment]
Address #137 and #121 perhaps?

**Comment by kanderso-nrel** [comment]
Is there a rush for #121?  So long as the older pandas versions aren't causing any problems I don't see a reason to drop them.

**Comment by cwhanse** [comment]
No rush and if you aren't concerned about #137, then neither am I.

**Comment by kperrynrel** [comment]
TODO on my end: documentation for systems module and orientation module (https://github.com/pvlib/pvanalytics/issues/133)

**Comment by kanderso-nrel** [comment]
Looks like #145 is the last thing left on the list before final release cleanup.  It's not critical but might be nice to get in if we're directing PVPMC audience members to our docs.  @cwhanse are you planning to look at that one, or should I go ahead and open a PR to finalize 0.1.2?

**Comment by cwhanse** [comment]
Merge #145 when you'd like, I approved.
