### ISSUE TITLE
Organize examples by topic or pvanalytics code module.

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvanalytics#154]
@kperrynrel you've done such a good job that we need subheadings for the examples :)

**Comment by kanderso-nrel** [comment]
Documenting something that had me flummoxed for a while when I set this up for pvlib: each subdirectory has to have its own `README.rst` or else it doesn't show up in the rendered gallery.  See https://github.com/pvlib/pvlib-python/tree/master/docs/examples
