### ISSUE TITLE
Remove 'keep_tz' from '_calc_pathlength' function in metrics.py

### ISSUE THREAD

**Issue by abhisheksparikh** [pvlib/pvanalytics#168]
I got the following warning when using the variability_index function:

`FutureWarning: The 'keep_tz' keyword in DatetimeIndex.to_series is deprecated and will be removed in a future version.  You can stop passing 'keep_tz' to silence this warning.`

I would like to remove this and see what the effects are. Thoughts?

**Comment by cwhanse** [comment]
Thanks for mentioning this. I would say to keep it until it's removed; someone may be using Series without localized datetimes. Please leave the issue open to remind us to remove it in the future.
