### ISSUE TITLE
v0.1.3 planning

### ISSUE THREAD

**Issue by kanderso-nrel** [pvlib/pvanalytics#175]
Shall we aim for a release next week?  It's been ~3 months since 0.1.2 and we've got some nice things waiting to go out ([whatsnew](https://github.com/pvlib/pvanalytics/blob/main/docs/whatsnew/0.1.3.rst)).

@kperrynrel what are your thoughts on #146?

@abhisheksparikh I think we'd be happy to have #167 if it's ready in time, but also no big deal to push it to the next release if you don't have bandwidth available right now. 

If anyone has additional items they'd like to get into 0.1.3 (thermopile offsets?), feel free to add them to the [milestone](https://github.com/pvlib/pvanalytics/milestone/3) and solicit reviews.

**Comment by abhisheksparikh** [comment]
Yes, I want to complete the GHI and POA quality checks in #167. I will get the GHI check in by 12/11.

**Comment by kperrynrel** [comment]
@kanderso-nrel I just went over #146  again and saw it's only doing an example for the pvwatts orientation method, which I'm currently more comfortable with than the infer_orientation_daily_peak() method (Matt's original implementation is yielding different results from the pvanalytics implementation, which is less accurate). I'm okay with picking this back up here today and getting it squared away for the next version release. I'll need to eventually retool infer_orientation_daily_peak() to get it more accurate/faster.
