### ISSUE TITLE
Consider switching sphinx themes

### ISSUE THREAD

**Issue by kanderso-nrel** [pvlib/pvanalytics#176]
Our docs currently use the `alabaster` theme, resulting in a website which I (very subjectively) find a little difficult to read and navigate.  Compare with docs built with other themes:

- pvanalytics (alabaster): https://pvanalytics.readthedocs.io/en/stable/whatsnew/0.1.2.html
- pvlib (pydata-sphinx-theme): https://pvlib-python.readthedocs.io/en/latest/whatsnew.html
- rdtools (rtd-sphinx-theme): https://rdtools.readthedocs.io/en/stable/changelog.html
- twoaxistracking (sphinx_book_theme): https://twoaxistracking.readthedocs.io/en/stable/

I'd like to switch to another theme, but I don't have a strong opinion on what new theme to choose.  Some considerations:

Themes affect not just font and styling but also navigation.  For example, the pydata-sphinx-theme separates out top-level navigation to a top navbar instead of putting the entire website tree in the left sidebar.  See examples of many themes here: https://sphinx-themes.org/#themes

The three `pvlib/*` projects with sphinx docs currently use three different themes.  Using the same theme across multiple projects might be helpful in that experience using a theme in one project would transfer to another.  It may also help with "branding" the pvlib family, if that's something we are interested in.  One downside of using the same theme for all projects is that it might be harder to know which project you're looking at if all of our docs look the same.

**Comment by cwhanse** [comment]
I somewhat prefer the new pvlib-python theme (pydata) over the current pvanalytics theme (alabaster). I don't like the rtd-sphinx theme; perhaps because that's what pvlib-python just left.

I note that both numpy and scipy use the pydata theme and their home documentation pages look very similar. In fact, both suggest that we're putting too much content on the home documentation page.

**Comment by bt-** [comment]
I’ve been finding the latest pvlib docs very pleasant to navigate and I
think it would be helpful to have consistent themes. Not sure if anyone
references it other than me, but I’m open to changing pvcaptest to match.
