### ISSUE TITLE
Quantify power losses due to snow cover

### ISSUE THREAD

**Issue by eccoope** [pvlib/pvanalytics#200]
Hi, I've developed a method to quantify utility-scale power losses due to snow cover (presented at the 2023 PVSC and the 2023 EUPVSEC - [PVSC_Proceedings_2023.pdf](https://github.com/pvlib/pvanalytics/files/13282907/PVSC_Full_Proceedings_2023.1.pdf) and
[EUPVSEC_2023.pdf](https://github.com/pvlib/pvanalytics/files/13282910/EPJ_SNOW_2023_SHORT.pdf). Several potential collaborators have asked for a code implementation. The implementation would include anonymized example data provided by a utility partner, and would use the functions provided in clipping.py along with performance modeling functions hosted by pvlib. It would most likely be an example .ipynb, with the potential to create a new module pvanalytics.snow to house functions that solve for effective transmission of the snow cover and the fractional area of opaque snow cover. Would pv-analytics be willing to host this?

**Comment by cwhanse** [comment]
> Would pv-analytics be willing to host this?

I'll say yes. There's great interest in this topic. A snow loss algorithm may be a bit different than other algorithms in pvanalytics. The inputs would be time series (power, voltage, etc.) but the output is likely to be a time series at a coarser scale (e.g. daily). 

My other reaction is that `snow` would go into a new family of modules, perhaps `pvanalytics.losses.snow`, to accompany other types of loss calculators (clipping, soiling, etc.)
