### ISSUE TITLE
Power, irradiance, and temperature examples from PV Fleets pipeline?

### ISSUE THREAD

**Issue by kperrynrel** [pvlib/pvanalytics#201]
Hey @kandersolar and @cwhanse since we have the logic for time shifts now merged into main, I wanted to ask if we'd be interested in adding some example notebooks illustrating the QA process that we've been using in Fleets (for temperature, irradiance, and power/energy streams):

https://github.com/kperrynrel/fleets_qa_examples/tree/main 

I know we want to keep this repo pipeline-agnostic, so these would just act as a couple of examples which illustrate how our group is using PVAnalytics functions in our work. I still need to integrate the new time shift logic into these examples (it's literally plugging in the new functions), but these could be just jupyter notebook examples, or I can integrate them as examples into Sphinx. No worries if we're not interested, but as I'm pointing multiple people towards this example repo, it could be valuable to include. Let me know your thoughts!

**Comment by cwhanse** [comment]
@kperrynrel those would be welcomed. The base layer of functions is agnostic to workflow but we envisioned adding a layer above with various pipelines, similar to the ModelChain concept in pvlib.

**Comment by kperrynrel** [comment]
Awesome! Would we want to mimic Pvlib formatting, and add these as jupyter notebooks under a /tutorials/ folder, as so? 
![image](https://github.com/pvlib/pvanalytics/assets/70228568/6202db1a-df77-46f6-84f4-11edbb9a7dc8)
I can start working this PR here this week once we make a decision on where/how we'd want to include these.

**Comment by cwhanse** [comment]
I think we'd rather have examples as .py files as in the [pvlib example](https://github.com/pvlib/pvlib-python/tree/main/docs/examples) gallery, but I'll defer to @kandersolar here.

**Comment by kandersolar** [comment]
Yes, .py files are much preferred over .ipynb.  A new folder in the [examples](https://github.com/pvlib/pvanalytics/tree/main/docs/examples) to create a new section in the [gallery](https://pvanalytics.readthedocs.io/en/latest/generated/gallery/index.html) sounds good to me.

**Comment by kperrynrel** [comment]
Sounds good @kandersolar and @cwhanse, I will start working up a PR for this now. Thanks!
