### ISSUE TITLE
Add shadow detection

### ISSUE THREAD

**Issue by wfvining** [pvlib/pvanalytics#24]
Should go in the `features` module, I think.

**Comment by rjstephens** [comment]
Are you referring to shading of a pyranometer or on the panels?

**Comment by cwhanse** [comment]
Both, I think. We want the library to be capable of hosting shadow detection algorithms of various types and uses.

We have an algorithm that can process a time series of irradiance (at ~1min resolution) to label times when the sensor was shaded, which finds shadows that correlate across days (e.g., from nearby poles or wires). It won't reliably identify shadows from soiled sensors. It's a research project to see if, and how, the algorithm can be extended to time-averaged irradiance or power data.

**Comment by rjstephens** [comment]
Ok that sounds good. 

Would doing a comparison between the pyranometers at each combination of azimuth and elevation be enough to indicate if a given pyranomter is shaded by a fixed object such as a pole as you mention? I have had success in the past doing this on 15 minute resolution irradiance data.

Do you have a link to any further information on this algorithm and project?

**Comment by cwhanse** [comment]
The algorithm I'd like to publish processes one sensor at a time. Having multiple sensors is a different approach. From pvanalytics perspective both techniques are welcome, and we can let users decide which works best for them.

We had a preprint in review that describes the algorithm, then the first author left and I never got it finished. Illustration of the algorithm's output is in this [report](https://www.osti.gov/servlets/purl/1232609), and there is [code](https://github.com/sandialabs/MATLAB_PV_LIB/blob/master/pvl_detect_shadows.m) in PVLib for Matlab.
