### ISSUE TITLE
Function to calculate the Variability Index

### ISSUE THREAD

**Issue by bt-** [pvlib/pvanalytics#60]
I have a function somewhere that calculates the variability index (VI).  I think this package would be a good home for it and I'd be happy to contribute it if there is a place for it.

The features module might be an appropriate place, but a daily float value for VI is returned rather than a boolean.

**Comment by wfvining** [comment]
Thanks, @bt-, your contribution would be greatly appreciated! One of our main goals is to provide a home for these kinds of things.

Generally we have been naming things `features.<feature>.<method>` (in this case that would be `features.variability.<bt-s_method>()`) as a way to keep organized and keep space for several different methods to calculate the same feature. The other place that might be good for it is in `metrics`. We don't have anything there yet. What do you think @cwhanse?

**Comment by cwhanse** [comment]
In `pvanalytics.metrics`, I think. Thanks @bt-!
