### ISSUE TITLE
determine if a time series is DST aware or not

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvanalytics#66]
I'd like a function that tells me if a time series uses a fixed offset timezone like `'Etc/GMT+7'` or a DST aware timezone like `'America/Denver'`.

In the PV world, we often don't have data that would occur right at the DST transition (2 am local). So my suggestion is to find the sunrise, sunset, and/or solar noon in the ~7 days before and after a DST transition. Then determine if there's a 1 hour shift in that data.

**Comment by wfvining** [comment]
I have been working on porting some code from PVFleets that detects time-shifts in general (DST as well as time shifts as short as 15 minutes). It works in a similar way to your suggestion.

The first thing in the pipeline for this is detecting sunrise and sunset in power or irradiance data I already have some work in progress for this and should draft a PR soon.
