### ISSUE TITLE
orientation._freqstr_to_hours returns minutes not hours

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvanalytics#72]
Should [this line](https://github.com/pvlib/pvanalytics/blob/7104074be64de911ea2eafa6f97ddd3c1e444799/pvanalytics/features/orientation.py#L60) be ' / 3600'?

**Comment by wfvining** [comment]
Yes. It should.

I think that function should also be rewritten to use the `tseries` API which I was not aware of until recently:

```python
from pandas.tseries import frequencies

# ...
def _freqstr_to_hours(freq):
    pd.to_timedelta(frequencies.to_offset(freq)).seconds / 3600
```
