### ISSUE TITLE
scipy.stats.median_absolute_deviation is deprecated

### ISSUE THREAD

**Issue by wfvining** [pvlib/pvanalytics#80]
Getting a warning from the tests for `pvanalytics.quality.outliers`

### From the deprecation warning:

use `median_abs_deviation` instead!
  
  To preserve the existing default behavior, use `scipy.stats.median_abs_deviation(..., scale=1/1.4826)`. The value 1.4826 is not numerically precise for scaling with a normal distribution. For a numerically precise value, use `scipy.stats.median_abs_deviation(..., scale='normal')`.

**Comment by cwhanse** [comment]
OK to switch function names from `median_absolute_deviation` to `median_abs_deviation(..., scale='normal')` [here](https://github.com/pvlib/pvanalytics/blob/f6bd37acd1a86c545b2e879b1f5d3d720835c3f3/pvanalytics/quality/outliers.py#L98)

Looks minor to me

**Comment by wfvining** [comment]
It should be that simple, but `test_hampel_max_deviation` is failing when I change it.
