### ISSUE TITLE
Handle missing data gracefully in clipping.levels()

### ISSUE THREAD

**Issue by wfvining** [pvlib/pvanalytics#96]
`features.clipping.levels()` raises some very difficult to decipher value errors form numpy when there are NAs in the data. We should either raise a more meaningful and useful exception or simply deal with NAs by dropping them, applying the clipping filter, reindexing, and filling missing values with `False`.

**Comment by cwhanse** [comment]
Can you link an example?

**Comment by wfvining** [comment]
Running this:

```python
daytime_power = power.copy()
daytime_power[power < 100] = pd.NA
clip_levels = clipping.levels(daytime_power)
```

Results in `ValueError: autodetected range of [nan, nan] is not finite` from `numpy.histograms`

If you do `clipping.levels(daytime_power.dropna())` it works as expected, but you need to reindex the mask if you want to use it on the original data. My suggestion is to do the `dropna()` and `reindex()` inside `clipping.levels()`.

Alternatively we can add to the documentation that the data must not contain undefined values and raise an exception with a meaningful/useful error message when undefined values are present.
